just : ep.maco alignjust.maco atoi.maco normalprint.maco puts.maco
	./maclk just.mac ep.maco alignjust.maco atoi.maco normalprint.maco puts.maco

ep.maco : ep.as
	./macas ep.as

alignjust.maco : alignjust.as
	./macas alignjust.as
atoi.maco : atoi.as
	./macas atoi.as
normalprint.maco : normalprint.as
	./macas normalprint.as
puts.maco : puts.as
	./macas puts.as	

clean :
	rm *.maco
